gpu: drm/mediatek_v2: Fix double type usage in debug message
The aapcs ABI used for the kernel build does not support passing double
types to variadic functions like printk. The use of %f with a floating-point
macro MSYNC_MIN_FPS in a DDPDBG call causes a build failure.

To resolve this, cast the floating-point value to an integer and update
the format specifier in the debug message from %f to %d.

../drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_crtc.c:7349:3: error: 'mtk_dprec_logger_pr' requires 'double' type support, but ABI 'aapcs' does not support it
 7349 |                 DDPDBG("[Msync] min fps:%f, fps:%d, time_diff:%d\n", MSYNC_MIN_FPS, fps, time_diff);
      |                 ^
../drivers/gpu/drm/mediatek/mediatek_v2/mtk_log.h:46:3: note: expanded from macro 'DDPDBG'
   46 |                 mtk_dprec_logger_pr(DPREC_LOGGER_DEBUG, fmt, ##arg);           \
      |                 ^
../drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_crtc.c:7349:3: error: 'printk' requires 'double' type support, but ABI 'aapcs' does not support it
../drivers/gpu/drm/mediatek/mediatek_v2/mtk_log.h:48:4: note: expanded from macro 'DDPDBG'
   48 |                         pr_info("[DISP]" pr_fmt(fmt), ##arg);     \
      |                         ^
../include/linux/printk.h:419:2: note: expanded from macro 'pr_info'
  419 |         printk(KERN_INFO pr_fmt(fmt), ##__VA_ARGS__)
      |         ^
2 errors generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>