drivers: misc: mediatek: sensorhub: Fix missing variable type
../drivers/misc/mediatek/sensor/2.0/sensorhub/transceiver.c:735:8: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
  735 | static transceiver_selftest(struct hf_device *hf_dev,
      | ~~~~~~ ^
      | int

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>