drivers: misc: mediatek: tcpc_cps8851: Drop unused variable
../drivers/misc/mediatek/typec/tcpc/tcpc_cps8851.c:855:9: error: variable 'ret' set but not used [-Werror,-Wunused-but-set-variable]
  855 |     int ret;
      |         ^

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>