drivers: misc: mediatek: tcpc_et7304: Fix unused variables preprocessor issue
These variables appear unused to the preprocessor because the RT1711_INFO macro
may expand to do nothing, depending on the build configuration.

../drivers/misc/mediatek/typec/tcpc/tcpc_et7304.c:196:9: error: variable 't1' set but not used [-Werror,-Wunused-but-set-variable]
  196 |     u64 t1 = 0, t2 = 0;
      |         ^
../drivers/misc/mediatek/typec/tcpc/tcpc_et7304.c:196:17: error: variable 't2' set but not used [-Werror,-Wunused-but-set-variable]
  196 |     u64 t1 = 0, t2 = 0;
      |                 ^
../drivers/misc/mediatek/typec/tcpc/tcpc_et7304.c:217:9: error: variable 't1' set but not used [-Werror,-Wunused-but-set-variable]
  217 |     u64 t1 = 0, t2 = 0;
      |         ^
../drivers/misc/mediatek/typec/tcpc/tcpc_et7304.c:217:17: error: variable 't2' set but not used [-Werror,-Wunused-but-set-variable]
  217 |     u64 t1 = 0, t2 = 0;
      |

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>