drivers: misc: mediatek: fpsgo_v3: Fix missing variable type
../drivers/misc/mediatek/performance/fpsgo_v3/fstb/fstb.c:110:8: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
  110 | static set_cam_active_fpsgo_off;
      | ~~~~~~ ^
      | int

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>