drivers: misc: mediatek: tcpci_typec: Fix missing function typec
../drivers/misc/mediatek/typec/tcpc/tcpci_typec.c:22:8: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
   22 | extern gxy_usb_set_usbccflag( enum gxy_usb_orient cc_flag);
      | ~~~~~~ ^
      | int

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>