drivers: misc: mediatek: tcpc_cps8851: Fix unused variables preprocessor issue
These variables appear unused to the preprocessor because the CPS8851_INFO macro
may expand to do nothing, depending on the build configuration.

../drivers/misc/mediatek/typec/tcpc/tcpc_cps8851.c:183:9: error: variable 't1' set but not used [-Werror,-Wunused-but-set-variable]
  183 |     u64 t1 = 0, t2 = 0;
      |         ^
../drivers/misc/mediatek/typec/tcpc/tcpc_cps8851.c:183:17: error: variable 't2' set but not used [-Werror,-Wunused-but-set-variable]
  183 |     u64 t1 = 0, t2 = 0;
      |                 ^
../drivers/misc/mediatek/typec/tcpc/tcpc_cps8851.c:204:9: error: variable 't1' set but not used [-Werror,-Wunused-but-set-variable]
  204 |     u64 t1 = 0, t2 = 0;
      |         ^
../drivers/misc/mediatek/typec/tcpc/tcpc_cps8851.c:204:17: error: variable 't2' set but not used [-Werror,-Wunused-but-set-variable]
  204 |     u64 t1 = 0, t2 = 0;
      |                 ^

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>