drivers: misc: mediatek: iommu: Fix missing function type
../drivers/misc/mediatek/iommu/iommu_secure.c:230:1: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
  230 | mtk_iommu_secure_bk_tf_dump(uint32_t type, uint32_t id, uint32_t bank,
      | ^

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>